plugins {
    id 'java'
    id 'application'
}

group = 'com.crawler'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.jsoup:jsoup:1.17.2'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'org.assertj:assertj-core:3.25.3'
}

application {
    mainClass = 'com.crawler.App'
}

tasks.named('test') {
    useJUnitPlatform()
}
